export const movies = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    titleRu: "Побег из Шоушенка",
    year: 1994,
    rating: 9.2,
    poster: "https://images-na.ssl-images-amazon.com/images/I/51NiGlapXlL.jpg",
    description: "Заключённый Энди Дюфрейн пытается сохранить надежду и человечность, сталкиваясь с жестокостью тюрьмы Шоушенк.",
    fullDescription: "Несправедливо осуждённый банкир Энди Дюфрейн попадает в тюрьму Шоушенк, где правят жёсткие правила и безнадёжность. Не теряя достоинства, он постепенно находит общий язык с заключёнными и завоёвывает уважение, оставаясь верным идее внутренней свободы. История о стойкости, дружбе и тихой силе, которая меняет людей вокруг — без громких лозунгов и без спойлеров, но с редким ощущением надежды.",
    country: "США",
    genres: "Драма, криминал",
    director: "Фрэнк Дарабонт",
    actors: "Тим Роббинс, Морган Фриман, Боб Гантон",
    duration: "142 мин",
    trailer: "https://www.youtube.com/watch?v=NmzuHjWmXOc",
    kinopoiskId: 326,
    imdb: "https://www.imdb.com/title/tt0111161",
  },
  {
    id: 2,
    title: "The Godfather",
    titleRu: "Крёстный отец",
    year: 1972,
    rating: 9.1,
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
    description: "История семьи Корлеоне, которая сталкивается с предательством, властью и борьбой за влияние в криминальном мире.",
    fullDescription: "Сага о семье Корлеоне — не просто криминальная драма, а тонкий портрет власти, традиций и цены лояльности. Когда обстоятельства вынуждают клан перестраивать своё влияние, личное становится политическим, а семейные решения — судьбоносными. Фильм удерживает баланс между холодным расчётом и человеческими чувствами, показывая, как меняются роли, принципы и границы дозволенного — без пересказа ключевых поворотов.",
    country: "США",
    genres: "Драма, криминал",
    director: "Фрэнсис Форд Коппола",
    actors: "Марлон Брандо, Аль Пачино, Джеймс Кан",
    duration: "175 мин",
    trailer: "https://www.youtube.com/watch?v=EzNhaLUT520",
    kinopoiskId: 325,
    imdb: "https://www.imdb.com/title/tt0068646",
  },
  {
    id: 3,
    title: "The Dark Knight",
    titleRu: "Тёмный рыцарь",
    year: 2008,
    rating: 9,
    poster: "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
    description: "Бэтмен противостоит Джокеру, преступнику, который стремится разрушить Готэм, используя хаос как оружие.",
    fullDescription: "Готэм на грани — город пытается поверить в справедливость, но хаос находит новые формы. Бэтмен действует на пределе возможностей, сталкиваясь с противником, который не играет по правилам и проверяет людей на прочность. Это напряжённый триллер о выборе, ответственности и том, как хрупки моральные опоры, когда ставки становятся слишком высокими. Атмосфера, темп и конфликт держат до финала — без раскрытия поворотных моментов.",
    country: "США, Великобритания",
    genres: "Боевик, криминал, драма",
    director: "Кристофер Нолан",
    actors: "Кристиан Бэйл, Хит Леджер, Аарон Экхарт",
    duration: "152 мин",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    kinopoiskId: 111543,
    imdb: "https://www.imdb.com/title/tt0468569",
  },
  {
    id: 4,
    title: "12 Angry Men",
    titleRu: "12 разгневанных мужчин",
    year: 1957,
    rating: 9,
    poster: "https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg",
    description: "Двенадцать присяжных обсуждают судьбу обвиняемого, и один человек пытается убедить остальных пересмотреть доказательства.",
    fullDescription: "В закрытой комнате двенадцать присяжных должны вынести вердикт, но обсуждение быстро превращается в столкновение характеров и убеждений. Один голос сомнения заставляет шаг за шагом проверять факты, логику и собственные предрассудки. Почти без смены локаций фильм держит напряжение диалогами и точной психологией: кто-то спешит закончить, кто-то цепляется за привычное, а правда требует терпения. Классика, которая раскрывается через детали — без спойлеров.",
    country: "США",
    genres: "Драма, криминал",
    director: "Сидни Люмет",
    actors: "Мартин Балсам, Джон Фиделия, Ли Дж. Кобб",
    duration: "96 мин",
    trailer: "https://www.youtube.com/watch?v=A7CBVER0glE",
    kinopoiskId: 346,
    imdb: "https://www.imdb.com/title/tt0050083",
  },
  {
    id: 5,
    title: "Schindler's List",
    titleRu: "Список Шиндлера",
    year: 1993,
    rating: 8.9,
    poster: "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
    description: "Оскар Шиндлер спасает более тысячи евреев во время Холокоста, рискуя собственной жизнью.",
    fullDescription: "На фоне катастрофы Второй мировой войны предприниматель Оскар Шиндлер начинает с прагматичных целей, но постепенно его выборы меняются. Фильм бережно и без сенсационности показывает человеческое достоинство в нечеловеческих условиях: страх, надежду, хрупкие жесты поддержки и цену каждого решения. Это тяжёлая, но важная история о том, как личная ответственность может проявиться там, где кажется, что всё предрешено. Без спойлеров, но с сильным эмоциональным послевкусием.",
    country: "США",
    genres: "Драма, история",
    director: "Стивен Спилберг",
    actors: "Лиам Нисон, Ральф Файнс, Бен Кингсли",
    duration: "195 мин",
    trailer: "https://www.youtube.com/watch?v=gG22XNhtnoY",
    kinopoiskId: 329,
    imdb: "https://www.imdb.com/title/tt0108052",
  },
  {
    id: 6,
    title: "Pulp Fiction",
    titleRu: "Криминальное чтиво",
    year: 1994,
    rating: 8.9,
    poster: "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
    description: "Несколько историй о гангстерах, боксере, гангстерской жене и паре бандитов в городе Лос-Анджелесе.",
    fullDescription: "Несколько сюжетных линий в Лос‑Анджелесе переплетаются в нестандартной структуре, где сцены складываются как мозаика. Герои — гангстеры, случайные авантюристы и люди, попавшие не в то место и не в то время — постоянно балансируют между абсурдом и опасностью. Фильм цепляет диалогами, ритмом и неожиданными тональными поворотами, оставаясь при этом удивительно цельным. Культовая криминальная история без пересказа ключевых событий.",
    country: "США",
    genres: "Криминал, драма",
    director: "Квентин Тарантино",
    actors: "Джон Траволта, Сэмюэль Л. Джексон, Ума Турман",
    duration: "154 мин",
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqJDE",
    kinopoiskId: 342,
    imdb: "https://www.imdb.com/title/tt0110912",
  },
  {
    id: 7,
    title: "Inception",
    titleRu: "Начало",
    year: 2010,
    rating: 8.8,
    poster: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    description: "Вор, умеющий проникать в подсознание людей во время сна, получает возможность изменить будущее влиятельного человека.",
    fullDescription: "Команда специалистов берётся за рискованную миссию в пространстве снов, где правила реальности меняются на ходу. Чем глубже погружение, тем сложнее отличить план от импровизации, а внутренние страхи — от внешних препятствий. Фильм впечатляет визуальными решениями и точной механикой напряжения: каждая сцена работает как часть большой конструкции. Это интеллектуальный экшен о памяти, вине и выборе, рассказанный без раскрытия ключевых загадок.",
    country: "США, Великобритания",
    genres: "Боевик, научная фантастика, триллер",
    director: "Кристофер Нолан",
    actors: "Леонардо ДиКаприо, Мэрион Котийар, Эллен Пейдж",
    duration: "148 мин",
    trailer: "https://www.youtube.com/watch?v=YoHD_XwIlNY",
    kinopoiskId: 447301,
    imdb: "https://www.imdb.com/title/tt1375666",
  },
  {
    id: 8,
    title: "Forrest Gump",
    titleRu: "Форрест Гамп",
    year: 1994,
    rating: 8.8,
    poster: "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
    description: "История жизни человека с низким IQ, который волей судьбы становится участником важных событий американской истории.",
    fullDescription: "Форрест Гамп — человек с простым взглядом на мир и редкой искренностью, который неожиданно оказывается рядом с важными событиями эпохи. Его путь — это не столько хроника достижений, сколько история о доброте, верности и способности идти вперёд, даже когда всё вокруг меняется. Фильм сочетает юмор и трогательность, оставляя после себя светлое ощущение и много точных наблюдений о людях. Без спойлеров, но с той самой «теплотой», за которую его любят.",
    country: "США",
    genres: "Драма, романтика",
    director: "Роберт Земекис",
    actors: "Том Хэнкс, Гэри Синиз, Салли Филд",
    duration: "142 мин",
    trailer: "https://www.youtube.com/watch?v=bIvC-5paragE",
    kinopoiskId: 448,
    imdb: "https://www.imdb.com/title/tt0109830",
  },
  {
    id: 9,
    title: "The Matrix",
    titleRu: "Матрица",
    year: 1999,
    rating: 8.7,
    poster: "https://images-na.ssl-images-amazon.com/images/I/51EG732BV3L.jpg",
    description: "Хакер обнаруживает, что его мир на самом деле развитая симуляция, созданная разумными машинами.",
    fullDescription: "Обычная жизнь внезапно начинает трещать по швам, когда Нео сталкивается с намёками на скрытую правду о мире. Погружаясь в загадочную сеть людей и идей, он вынужден переосмыслить реальность, выбор и собственную роль. «Матрица» сочетает философию, стиль и динамику, задавая вопросы о свободе воли и природе контроля. Фильм держит интригу и ритм, не раскрывая заранее ключевых открытий.",
    country: "США",
    genres: "Боевик, научная фантастика",
    director: "Лана Вачовски, Лили Вачовски",
    actors: "Киану Ривз, Лоуренс Фишберн, Керри-Энн Мосс",
    duration: "136 мин",
    trailer: "https://www.youtube.com/watch?v=jYzcLE7L7Ps",
    kinopoiskId: 301,
    imdb: "https://www.imdb.com/title/tt0133093",
  },
  {
    id: 10,
    title: "Interstellar",
    titleRu: "Интерстеллар",
    year: 2014,
    rating: 8.6,
    poster: "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    description: "Группа астронавтов путешествует через кротовую нору в попытке найти новую планету для человечества.",
    fullDescription: "Когда будущее человечества оказывается под угрозой, группа исследователей отправляется в путешествие за пределы привычного — туда, где время и расстояния ведут себя иначе. Фильм соединяет масштабную научную фантастику с очень личной историей о связи, ответственности и надежде. Он впечатляет музыкой, визуальной мощью и ощущением космического одиночества, оставаясь при этом эмоционально точным. Интрига и открытия раскрываются постепенно — без спойлеров.",
    country: "США, Великобритания, Канада",
    genres: "Боевик, научная фантастика, драма",
    director: "Кристофер Нолан",
    actors: "Мэттью Макконахи, Энн Хэтэуэй, Майкл Кейн",
    duration: "169 мин",
    trailer: "https://www.youtube.com/watch?v=zSAJ0l4OBLU",
    kinopoiskId: 258687,
    imdb: "https://www.imdb.com/title/tt0816692",
  },
  {
    id: 11,
    title: "Taxi Driver",
    titleRu: "Таксист",
    year: 1976,
    rating: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/ekstpH614fwDX8DUln1a2Opz0N8.jpg",
    description: "Ветеран Вьетнама работает ночным таксистом в Нью-Йорке.",
    fullDescription: "Ветеран Вьетнама работает ночным таксистом в Нью-Йорке.",
    country: "США",
    genres: "Криминал, драма",
    director: "Мартин Скорсезе",
    actors: "Роберт Де Ниро, Джоди Фостер",
    duration: "113 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 12,
    title: "No Country for Old Men",
    titleRu: "Старикам тут не место",
    year: 2007,
    rating: 8.1,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
    description: "Охотник находит чемодан с деньгами наркомафии.",
    fullDescription: "Охотник находит чемодан с деньгами наркомафии.",
    country: "США",
    genres: "Криминал, драма, триллер",
    director: "Братья Коэн",
    actors: "Хавьер Бардем, Джош Бролин",
    duration: "122 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 13,
    title: "The Silence of the Lambs",
    titleRu: "Молчание ягнят",
    year: 1991,
    rating: 8.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NzkzMDI4OF5BMl5BanBnXkFtZTcwMDA0NzE1NA@@._V1_SX300.jpg",
    description: "Курсантка ФБР обращается к маньяку Лектеру за помощью.",
    fullDescription: "Курсантка ФБР обращается к маньяку Лектеру за помощью.",
    country: "США",
    genres: "Криминал, триллер",
    director: "Джонатан Демме",
    actors: "Джоди Фостер, Энтони Хопкинс",
    duration: "118 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 14,
    title: "Scarface",
    titleRu: "Лицо со шрамом",
    year: 1983,
    rating: 8.3,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAzOTM4MzEwNl5BMl5BanBnXkFtZTgwMzU1OTc1MDE@._V1_SX300.jpg",
    description: "Кубинский эмигрант строит наркоимперию в Майами.",
    fullDescription: "Кубинский эмигрант строит наркоимперию в Майами.",
    country: "США",
    genres: "Криминал, драма",
    director: "Брайан Де Пальма",
    actors: "Аль Пачино, Мишель Пфайффер",
    duration: "170 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 15,
    title: "Black Swan",
    titleRu: "Чёрный лебедь",
    year: 2010,
    rating: 8,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BNzY2NzI4OTE5MF5BMl5BanBnXkFtZTcwMjMyNDY4Mw@@._V1_SX300.jpg",
    description: "Балерина получает главную роль и теряет рассудок.",
    fullDescription: "Балерина получает главную роль и теряет рассудок.",
    country: "США",
    genres: "Драма, триллер",
    director: "Даррен Аронофски",
    actors: "Натали Портман, Мила Кунис",
    duration: "108 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 16,
    title: "Memento",
    titleRu: "Помни",
    year: 2000,
    rating: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
    description: "Мужчина с потерей памяти ищет убийцу жены.",
    fullDescription: "Мужчина с потерей памяти ищет убийцу жены.",
    country: "США",
    genres: "Детектив, триллер",
    director: "Кристофер Нолан",
    actors: "Гай Пирс, Керри-Энн Мосс",
    duration: "113 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 17,
    title: "Rear Window",
    titleRu: "Окно во двор",
    year: 1954,
    rating: 8.5,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    description: "Фотограф шпионит за соседями и подозревает убийство.",
    fullDescription: "Фотограф шпионит за соседями и подозревает убийство.",
    country: "США",
    genres: "Детектив, триллер",
    director: "Альфред Хичкок",
    actors: "Джеймс Стюарт, Грейс Келли",
    duration: "112 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 18,
    title: "Shutter Island",
    titleRu: "Остров проклятых",
    year: 2010,
    rating: 8.2,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxMTIyNzMxMV5BMl5BanBnXkFtZTcwOTc4OTI3Mg@@._V1_SX300.jpg",
    description: "Маршал расследует исчезновение пациентки психбольницы.",
    fullDescription: "Маршал расследует исчезновение пациентки психбольницы.",
    country: "США",
    genres: "Детектив, триллер",
    director: "Мартин Скорсезе",
    actors: "Леонардо ДиКаприо, Марк Руффало",
    duration: "138 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 19,
    title: "Reservoir Dogs",
    titleRu: "Бешеные псы",
    year: 1992,
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
    description: "Выжившие после ограбления ищут предателя.",
    fullDescription: "Выжившие после ограбления ищут предателя.",
    country: "США",
    genres: "Криминал, триллер",
    director: "Квентин Тарантино",
    actors: "Харви Кейтель, Тим Рот",
    duration: "99 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 20,
    title: "Psycho",
    titleRu: "Психо",
    year: 1960,
    rating: 8.5,
    poster: "https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_SX300.jpg",
    description: "Секретарша останавливается в странном мотеле.",
    fullDescription: "Секретарша останавливается в странном мотеле.",
    country: "США",
    genres: "Триллер",
    director: "Альфред Хичкок",
    actors: "Энтони Перкинс, Джанет Ли",
    duration: "109 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 21,
    title: "Ratatouille",
    titleRu: "Рататуй",
    year: 2007,
    rating: 8,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg",
    description: "Крысёнок мечтает стать шеф-поваром в Париже.",
    fullDescription: "Крысёнок мечтает стать шеф-поваром в Париже.",
    country: "США",
    genres: "Мультфильм, комедия, семейный",
    director: "Брэд Бёрд",
    actors: "Пэттон Освальт, Иэн Холм",
    duration: "111 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 22,
    title: "The Hangover",
    titleRu: "Мальчишник в Вегасе",
    year: 2009,
    rating: 7.7,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU1MDA1MTYwMF5BMl5BanBnXkFtZTcwMDcxMzA1Mg@@._V1_SX300.jpg",
    description: "Друзья просыпаются в Вегасе без воспоминаний.",
    fullDescription: "Друзья просыпаются в Вегасе без воспоминаний.",
    country: "США",
    genres: "Комедия",
    director: "Тодд Филлипс",
    actors: "Брэдли Купер, Зак Галифианакис",
    duration: "100 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 23,
    title: "Lock, Stock and Two Smoking Barrels",
    titleRu: "Карты, деньги, два ствола",
    year: 1998,
    rating: 8.2,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyN2JmZmEtNjAyMy00NzYwLThmY2MtYWQ3OGNhNjExMmM4XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    description: "Четверо друзей проигрывают мафиози полмиллиона.",
    fullDescription: "Четверо друзей проигрывают мафиози полмиллиона.",
    country: "США",
    genres: "Комедия, криминал",
    director: "Гай Ричи",
    actors: "Джейсон Стэйтем, Ник Моран",
    duration: "107 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 24,
    title: "Beetlejuice",
    titleRu: "Битлджюс",
    year: 1988,
    rating: 7.5,
    poster: "https://m.media-amazon.com/images/M/MV5BYjkwNzVlNDEtMTJlNy00OTdlLTljYWItM2RkZmZkYzY3YjM2XkEyXkFqcGc@._V1_SX300.jpg",
    description: "Призраки нанимают «био-экзорциста» против новых жильцов.",
    fullDescription: "Призраки нанимают «био-экзорциста» против новых жильцов.",
    country: "США",
    genres: "Комедия, фэнтези",
    director: "Тим Бёртон",
    actors: "Алек Болдуин, Джина Дэвис",
    duration: "92 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 25,
    title: "The Truman Show",
    titleRu: "Шоу Трумана",
    year: 1998,
    rating: 8.1,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMDIzODcyY2EtMmY2MC00ZWVlLTgwMzAtMjQwOWUyNmJjNTYyXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
    description: "Человек узнаёт, что вся его жизнь — реалити-шоу.",
    fullDescription: "Человек узнаёт, что вся его жизнь — реалити-шоу.",
    country: "США",
    genres: "Комедия, драма",
    director: "Питер Уир",
    actors: "Джим Керри, Лора Линни",
    duration: "103 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 26,
    title: "Mary and Max",
    titleRu: "Мэри и Макс",
    year: 2009,
    rating: 8.1,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1NDIyNTA1Nl5BMl5BanBnXkFtZTcwMjc2Njk3OA@@._V1_SX300.jpg",
    description: "Дружба по переписке девочки и одинокого мужчины.",
    fullDescription: "Дружба по переписке девочки и одинокого мужчины.",
    country: "США",
    genres: "Мультфильм, комедия",
    director: "Адам Эллиот",
    actors: "Тони Коллетт, Филип Сеймур Хоффман",
    duration: "92 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 27,
    title: "Stardust",
    titleRu: "Звёздная пыль",
    year: 2007,
    rating: 7.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjkyMTE1OTYwNF5BMl5BanBnXkFtZTcwMDIxODYzMw@@._V1_SX300.jpg",
    description: "Юноша отправляется в волшебную страну за упавшей звездой.",
    fullDescription: "Юноша отправляется в волшебную страну за упавшей звездой.",
    country: "США",
    genres: "Приключения, фэнтези",
    director: "Мэттью Вон",
    actors: "Иэн Маккеллен, Клэр Дэйнс",
    duration: "127 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 28,
    title: "The Hobbit: The Desolation of Smaug",
    titleRu: "Хоббит: Пустошь Смауга",
    year: 2013,
    rating: 7.8,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_SX300.jpg",
    description: "Бильбо и гномы продолжают поход к Одинокой горе.",
    fullDescription: "Бильбо и гномы продолжают поход к Одинокой горе.",
    country: "США",
    genres: "Приключения, фэнтези",
    director: "Питер Джексон",
    actors: "Иэн Маккеллен, Мартин Фриман",
    duration: "161 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 29,
    title: "Apocalypto",
    titleRu: "Апокалипсис",
    year: 2006,
    rating: 7.8,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BNTM1NjYyNTY5OV5BMl5BanBnXkFtZTcwMjgwNTMzMQ@@._V1_SX300.jpg",
    description: "Молодой охотник бежит от жертвоприношения майя.",
    fullDescription: "Молодой охотник бежит от жертвоприношения майя.",
    country: "США",
    genres: "Боевик, приключения",
    director: "Мел Гибсон",
    actors: "Руди Янгблад, Далия Эрнандес",
    duration: "139 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 30,
    title: "The Deer Hunter",
    titleRu: "Охотник на оленей",
    year: 1978,
    rating: 8.1,
    poster: "https://m.media-amazon.com/images/M/MV5BZGI4YmVhMzMtMWExMS00MGZiLTg2MmItM2I2MWZjODAyM2U5XkEyXkFqcGc@._V1_SX300.jpg",
    description: "Война во Вьетнаме ломает жизни трёх друзей.",
    fullDescription: "Война во Вьетнаме ломает жизни трёх друзей.",
    country: "США",
    genres: "Драма, военный",
    director: "Майкл Чимино",
    actors: "Роберт Де Ниро, Кристофер Уокен",
    duration: "183 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 31,
    title: "Lost in Translation",
    titleRu: "Трудности перевода",
    year: 2003,
    rating: 7.7,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI2NDI5ODk4N15BMl5BanBnXkFtZTYwMTI3NTE3._V1_SX300.jpg",
    description: "Двое одиноких людей находят друг друга в Токио.",
    fullDescription: "Двое одиноких людей находят друг друга в Токио.",
    country: "США",
    genres: "Драма, мелодрама",
    director: "София Коппола",
    actors: "Скарлетт Йоханссон, Билл Мюррей",
    duration: "101 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 32,
    title: "Vicky Cristina Barcelona",
    titleRu: "Вики Кристина Барселона",
    year: 2008,
    rating: 7.1,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NDQ4MTg2MV5BMl5BanBnXkFtZTcwNDUzNjU3MQ@@._V1_SX300.jpg",
    description: "Две подруги влюбляются в художника в Барселоне.",
    fullDescription: "Две подруги влюбляются в художника в Барселоне.",
    country: "США",
    genres: "Драма, романтика",
    director: "Вуди Аллен",
    actors: "Скарлетт Йоханссон, Хавьер Бардем",
    duration: "96 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 33,
    title: "American Beauty",
    titleRu: "Красота по-американски",
    year: 1999,
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/wby9315QzVKdW9BonAefg8jGTTb.jpg",
    description: "Кризис среднего возраста отца семейства.",
    fullDescription: "Кризис среднего возраста отца семейства.",
    country: "США",
    genres: "Драма, романтика",
    director: "Сэм Мендес",
    actors: "Кевин Спейси, Аннетт Бенинг",
    duration: "122 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 34,
    title: "The Artist",
    titleRu: "Артист",
    year: 2011,
    rating: 7.9,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMzk0NzQxMTM0OV5BMl5BanBnXkFtZTcwMzU4MDYyNQ@@._V1_SX300.jpg",
    description: "Звезда немого кино встречает молодую танцовщицу.",
    fullDescription: "Звезда немого кино встречает молодую танцовщицу.",
    country: "США",
    genres: "Комедия, драма, мелодрама",
    director: "Мишель Хазанавичус",
    actors: "Жан Дюжарден, Беренис Бежо",
    duration: "100 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 35,
    title: "Chasing Amy",
    titleRu: "В погоне за Эми",
    year: 1997,
    rating: 7.2,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BZDM3MTg2MGUtZDM0MC00NzMwLWE5NjItOWFjNjA2M2I4YzgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    description: "Художник комиксов влюбляется в коллегу.",
    fullDescription: "Художник комиксов влюбляется в коллегу.",
    country: "США",
    genres: "Комедия, мелодрама",
    director: "Кевин Смит",
    actors: "Бен Аффлек, Джейсон Ли",
    duration: "113 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 36,
    title: "One Flew Over the Cuckoo's Nest",
    titleRu: "Пролетая над гнездом кукушки",
    year: 1975,
    rating: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
    description: "Преступник бросает вызов порядкам психбольницы.",
    fullDescription: "Преступник бросает вызов порядкам психбольницы.",
    country: "США",
    genres: "Драма",
    director: "Милош Форман",
    actors: "Джек Николсон, Луиза Флетчер",
    duration: "133 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 37,
    title: "Requiem for a Dream",
    titleRu: "Реквием по мечте",
    year: 2000,
    rating: 8.3,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTkzODMzODYwOF5BMl5BanBnXkFtZTcwODM2NjA2NQ@@._V1_SX300.jpg",
    description: "Зависимость разрушает мечты четырёх людей.",
    fullDescription: "Зависимость разрушает мечты четырёх людей.",
    country: "США",
    genres: "Драма",
    director: "Даррен Аронофски",
    actors: "Джаред Лето, Дженнифер Коннелли",
    duration: "102 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 38,
    title: "The Great Beauty",
    titleRu: "Великая красота",
    year: 2013,
    rating: 7.8,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ0ODg1OTQ2Nl5BMl5BanBnXkFtZTgwNTc2MDY1MDE@._V1_SX300.jpg",
    description: "Светский лев переосмысливает жизнь в Риме.",
    fullDescription: "Светский лев переосмысливает жизнь в Риме.",
    country: "США",
    genres: "Драма",
    director: "Паоло Соррентино",
    actors: "Тони Сервилло, Сабрина Ферилли",
    duration: "141 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 39,
    title: "City of God",
    titleRu: "Город Бога",
    year: 2002,
    rating: 8.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX300.jpg",
    description: "Два парня из трущоб Рио выбирают разные пути.",
    fullDescription: "Два парня из трущоб Рио выбирают разные пути.",
    country: "США",
    genres: "Криминал, драма",
    director: "Фернанду Мейреллиш",
    actors: "Алешандре Родригес",
    duration: "130 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 40,
    title: "Moneyball",
    titleRu: "Человек, который изменил всё",
    year: 2011,
    rating: 7.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxOTU3Mzc1M15BMl5BanBnXkFtZTcwMzk1ODUzNg@@._V1_SX300.jpg",
    description: "Менеджер создаёт команду с помощью статистики.",
    fullDescription: "Менеджер создаёт команду с помощью статистики.",
    country: "США",
    genres: "Биография, драма",
    director: "Беннетт Миллер",
    actors: "Брэд Питт, Джона Хилл",
    duration: "133 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 41,
    title: "L.A. Confidential",
    titleRu: "Секреты Лос-Анджелеса",
    year: 1997,
    rating: 8.2,
    poster: "https://m.media-amazon.com/images/M/MV5BODdiMjY1OGYtNDk0NC00NGQ1LWI4MDItOTJhMTM0YjE1YTAzXkEyXkFqcGc@._V1_SX300.jpg",
    description: "Три копа расследуют убийства в Лос-Анджелесе 50-х.",
    fullDescription: "Три копа расследуют убийства в Лос-Анджелесе 50-х.",
    country: "США",
    genres: "Криминал, детектив",
    director: "Кёртис Хэнсон",
    actors: "Рассел Кроу, Гай Пирс",
    duration: "138 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 42,
    title: "Lucky Number Slevin",
    titleRu: "Счастливое число Слевина",
    year: 2006,
    rating: 7.7,
    poster: "https://m.media-amazon.com/images/M/MV5BNzJkYjA4YjEtMTZlZi00NjFjLTgwNDMtN2VhYTY0MDU3ZjcwXkEyXkFqcGc@._V1_SX300.jpg",
    description: "Парень по ошибке попадает в войну двух боссов.",
    fullDescription: "Парень по ошибке попадает в войну двух боссов.",
    country: "США",
    genres: "Криминал, детектив",
    director: "Пол МакГиган",
    actors: "Джош Хартнетт, Брюс Уиллис",
    duration: "110 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 43,
    title: "Sid and Nancy",
    titleRu: "Сид и Нэнси",
    year: 1986,
    rating: 7,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjExNjA5NzY4M15BMl5BanBnXkFtZTcwNjQ2NzI5NA@@._V1_SX300.jpg",
    description: "Трагическая история басиста Sex Pistols.",
    fullDescription: "Трагическая история басиста Sex Pistols.",
    country: "США",
    genres: "Биография, драма",
    director: "Алекс Кокс",
    actors: "Гэри Олдман, Хлоя Уэбб",
    duration: "112 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 44,
    title: "Downfall",
    titleRu: "Бункер",
    year: 2004,
    rating: 8.2,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM1OTI1MjE2Nl5BMl5BanBnXkFtZTcwMTEwMzc4NA@@._V1_SX300.jpg",
    description: "Последние дни Третьего рейха в бункере Гитлера.",
    fullDescription: "Последние дни Третьего рейха в бункере Гитлера.",
    country: "США",
    genres: "Биография, драма, история",
    director: "Оливер Хиршбигель",
    actors: "Бруно Ганц, Александра Мария Лара",
    duration: "156 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 45,
    title: "Crocodile Dundee",
    titleRu: "Крокодил Данди",
    year: 1986,
    rating: 6.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg0MTU1MTg4NF5BMl5BanBnXkFtZTgwMDgzNzYxMTE@._V1_SX300.jpg",
    description: "Охотник на крокодилов приезжает в Нью-Йорк.",
    fullDescription: "Охотник на крокодилов приезжает в Нью-Йорк.",
    country: "США",
    genres: "Приключения, комедия",
    director: "Питер Фэйман",
    actors: "Пол Хоган, Линда Козловски",
    duration: "97 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 46,
    title: "Madagascar",
    titleRu: "Мадагаскар",
    year: 2005,
    rating: 6.9,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4NDUwMzQxMF5BMl5BanBnXkFtZTcwMDgwNjgyMQ@@._V1_SX300.jpg",
    description: "Четверо зверей из зоопарка попадают на Мадагаскар.",
    fullDescription: "Четверо зверей из зоопарка попадают на Мадагаскар.",
    country: "США",
    genres: "Мультфильм, приключения, комедия",
    director: "Эрик Дарнелл, Том МакГрат",
    actors: "Бен Стиллер, Крис Рок",
    duration: "86 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 47,
    title: "Despicable Me 2",
    titleRu: "Гадкий я 2",
    year: 2013,
    rating: 7.3,
    poster: "https://m.media-amazon.com/images/M/MV5BMTQxNzY1MjI5NF5BMl5BanBnXkFtZTcwNTI0MDY1OQ@@._V1_SX300.jpg",
    description: "Грю вербуют для борьбы с новым злодеем.",
    fullDescription: "Грю вербуют для борьбы с новым злодеем.",
    country: "США",
    genres: "Мультфильм, комедия, семейный",
    director: "Пьер Коффен, Крис Рено",
    actors: "Стив Карелл, Кристен Уиг",
    duration: "98 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 48,
    title: "Flight",
    titleRu: "Экипаж",
    year: 2012,
    rating: 7.3,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUxMjI1OTMxNl5BMl5BanBnXkFtZTcwNjc3NTY1OA@@._V1_SX300.jpg",
    description: "Пилот спасает рейс, но расследование вскрывает тайны.",
    fullDescription: "Пилот спасает рейс, но расследование вскрывает тайны.",
    country: "США",
    genres: "Драма, триллер",
    director: "Роберт Земекис",
    actors: "Дензел Вашингтон",
    duration: "138 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 49,
    title: "Match Point",
    titleRu: "Матч поинт",
    year: 2005,
    rating: 7.6,
    poster: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMzNzY4MzE5NF5BMl5BanBnXkFtZTcwMzQ1MDMzMQ@@._V1_SX300.jpg",
    description: "Бывший теннисист заводит опасный роман.",
    fullDescription: "Бывший теннисист заводит опасный роман.",
    country: "США",
    genres: "Драма, триллер",
    director: "Вуди Аллен",
    actors: "Джонатан Рис Майерс, Скарлетт Йоханссон",
    duration: "119 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  },
  {
    id: 50,
    title: "The Beach",
    titleRu: "Пляж",
    year: 2000,
    rating: 6.7,
    poster: "https://m.media-amazon.com/images/M/MV5BYTljNTg1YjktY2I3MS00MmQwLWJkYTAtYzcwZjRjM2ExNDJjXkEyXkFqcGc@._V1_SX300.jpg",
    description: "Американец ищет секретный райский остров.",
    fullDescription: "Американец ищет секретный райский остров.",
    country: "США",
    genres: "Приключения, драма",
    director: "Дэнни Бойл",
    actors: "Леонардо ДиКаприо",
    duration: "119 мин",
    trailer: "",
    kinopoiskId: null,
    imdb: "",
  }
];
